/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2022-01-13 06:09:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Gamut Gurus Technologies - Exclusive DevOps & Cloud Learning Hub</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/demos/style.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\">\r\n");
      out.write("<link href=\"css/sticky-footer-navbar.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- <script src=\"js/jquery.min.js\"></script> -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"#tabs\").tabs();\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<h1>Gamut Gurus DevOps & Cloud Learning Platform</h1> \r\n");
      out.write("\t\t\t<h4>Contact: +91-944897 1000 Email: info@gamutgurus.com</h4> \r\n");
      out.write("\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"tabs\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"#tabs-1\">DevOps</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#tabs-2\">Aws</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#tabs-3\">Cloud Platform</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#tabs-4\">Azure Cloud</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<div id=\"tabs-1\">\r\n");
      out.write("\t\t\t\t<p>https://en.wikipedia.org/wiki/DevOps</p>\r\n");
      out.write("\t\t\t\t<p>DevOps is a set of practices that combines software development (Dev) and IT operations (Ops). It aims to shorten the systems development life cycle and provide continuous delivery with high software quality.</p>\r\n");
      out.write("\t\t\t\t<p>From an academic perspective, Len Bass, Ingo Weber, and Liming Zhu â three computer science researchers from the CSIRO and the Software Engineering Institute â suggested defining DevOps as \"a set of practices intended to reduce the time between committing a change to a system and the change being placed into normal production, while ensuring high quality\".</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"tabs-2\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\tDocker has <a\r\n");
      out.write("\t\t\t\t\t\thref=\"http://www.actonmagic.com/blog/container-vs-virtualization/\">revolutionized\r\n");
      out.write("\t\t\t\t\t\tcontainerization</a> of applications allowing Devops to package any\r\n");
      out.write("\t\t\t\t\tapplication in a lightweight environment. The packaging is done in\r\n");
      out.write("\t\t\t\t\ta way which makes it as easy as installing a mobile app.It is\r\n");
      out.write("\t\t\t\t\tconsidered as most popular devops tools\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>It&nbsp;is a application container platform for build, ship\r\n");
      out.write("\t\t\t\t\tand run your distributed apps.Ecosystem includes:</p>\r\n");
      out.write("\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t<li>Docker Engine, a portable, lightweight run-time and\r\n");
      out.write("\t\t\t\t\t\tpackaging tool for building containerized apps.</li>\r\n");
      out.write("\t\t\t\t\t<li>Docker Hub, a cloud service for sharing apps and\r\n");
      out.write("\t\t\t\t\t\tautomating workflows.</li>\r\n");
      out.write("\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\tIt allows the&nbsp;developers containerize their apps and can run\r\n");
      out.write("\t\t\t\t\tthese apps anywhere. It is a powerful ecosystem where devops can\r\n");
      out.write("\t\t\t\t\tleverage many apps available on Docker Hub. It&nbsp;is built on the\r\n");
      out.write("\t\t\t\t\ttop of Linux containers. <a href=\"http://docker\">You can read\r\n");
      out.write("\t\t\t\t\t\tmore about Docker here</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"tabs-3\">\r\n");
      out.write("\t\t\t\t<p>Ansible is a configuration management tool or devops tools\r\n");
      out.write("\t\t\t\t\tthat is similar to Puppet and Chef.</p>\r\n");
      out.write("\t\t\t\t<p>Ansible is a very simple configuration language, I would say.\r\n");
      out.write("\t\t\t\t\tA beginner can write a basic script and deploy a few cloud\r\n");
      out.write("\t\t\t\t\tinstances in just a day.</p>\r\n");
      out.write("\t\t\t\t<p>For configuration management, its just too easy to learn and\r\n");
      out.write("\t\t\t\t\twrite in ANSIBLE as it understands âyamlâ format. Developer\r\n");
      out.write("\t\t\t\t\tfriendly and Devops friendly.</p>\r\n");
      out.write("\t\t\t\t<p>Ansible always runs in order and exits immediately when an\r\n");
      out.write("\t\t\t\t\terror occurs.&nbsp;Also while using Ansible, one has to know about\r\n");
      out.write("\t\t\t\t\tthe commands that they need to give. For example yum for redhat\r\n");
      out.write("\t\t\t\t\tdistributions and apt-get for ubuntu etc. In chef or puppet, they\r\n");
      out.write("\t\t\t\t\ttake care of translating to individual distribution and user need\r\n");
      out.write("\t\t\t\t\tnot worry about specifying correct commands as per the\r\n");
      out.write("\t\t\t\t\tdistribution.</p>\r\n");
      out.write("\t\t\t\t<p>Earlier windows was not supported in Ansible but with windows\r\n");
      out.write("\t\t\t\t\tsupported now, Ansible solves configuration problem at a small\r\n");
      out.write("\t\t\t\t\tscale.</p>\r\n");
      out.write("\t\t\t\t<p>But when it comes to scaling and complex configurations, of\r\n");
      out.write("\t\t\t\t\tcourse chef and puppet scores. As long as one is having 3 digits in\r\n");
      out.write("\t\t\t\t\tthe number of servers, ansible looks to be ok and beyond that one\r\n");
      out.write("\t\t\t\t\thas to choose Chef or Puppet.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"tabs-4\">\r\n");
      out.write("\t\t\t\t<p>Motorola</p>\r\n");
      out.write("\t\t\t\t<p>Apple</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div >\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<footer>@ 2020 Gamut Gurus Technologies. All rights Reserved.</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
